/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrdenesRouteImport } from './routes/ordenes'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as RepuestosRouteImport } from './routes/repuestos'
import { Route as VehiculosRouteImport } from './routes/vehiculos'
import { Route as ClientesCustomerIdRouteImport } from './routes/clientes_.$customerId'
import { Route as OrdenesOrderIdRouteImport } from './routes/ordenes_.$orderId'
import { Route as SystemWorkshopsRouteImport } from './routes/system.workshops'
import { Route as VehiculosVehicleIdRouteImport } from './routes/vehiculos_.$vehicleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdenesRoute = OrdenesRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const RepuestosRoute = RepuestosRouteImport.update({
  id: '/repuestos',
  path: '/repuestos',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculosRoute = VehiculosRouteImport.update({
  id: '/vehiculos',
  path: '/vehiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesCustomerIdRoute = ClientesCustomerIdRouteImport.update({
  id: '/clientes_/$customerId',
  path: '/clientes/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdenesOrderIdRoute = OrdenesOrderIdRouteImport.update({
  id: '/ordenes_/$orderId',
  path: '/ordenes/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemWorkshopsRoute = SystemWorkshopsRouteImport.update({
  id: '/system/workshops',
  path: '/system/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculosVehicleIdRoute = VehiculosVehicleIdRouteImport.update({
  id: '/vehiculos_/$vehicleId',
  path: '/vehiculos/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/equipo': typeof EquipoRoute
  '/login': typeof LoginRoute
  '/ordenes': typeof OrdenesRoute
  '/reportes': typeof ReportesRoute
  '/repuestos': typeof RepuestosRoute
  '/vehiculos': typeof VehiculosRoute
  '/clientes/$customerId': typeof ClientesCustomerIdRoute
  '/ordenes/$orderId': typeof OrdenesOrderIdRoute
  '/system/workshops': typeof SystemWorkshopsRoute
  '/vehiculos/$vehicleId': typeof VehiculosVehicleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/equipo': typeof EquipoRoute
  '/login': typeof LoginRoute
  '/ordenes': typeof OrdenesRoute
  '/reportes': typeof ReportesRoute
  '/repuestos': typeof RepuestosRoute
  '/vehiculos': typeof VehiculosRoute
  '/clientes/$customerId': typeof ClientesCustomerIdRoute
  '/ordenes/$orderId': typeof OrdenesOrderIdRoute
  '/system/workshops': typeof SystemWorkshopsRoute
  '/vehiculos/$vehicleId': typeof VehiculosVehicleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/equipo': typeof EquipoRoute
  '/login': typeof LoginRoute
  '/ordenes': typeof OrdenesRoute
  '/reportes': typeof ReportesRoute
  '/repuestos': typeof RepuestosRoute
  '/vehiculos': typeof VehiculosRoute
  '/clientes_/$customerId': typeof ClientesCustomerIdRoute
  '/ordenes_/$orderId': typeof OrdenesOrderIdRoute
  '/system/workshops': typeof SystemWorkshopsRoute
  '/vehiculos_/$vehicleId': typeof VehiculosVehicleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/equipo'
    | '/login'
    | '/ordenes'
    | '/reportes'
    | '/repuestos'
    | '/vehiculos'
    | '/clientes/$customerId'
    | '/ordenes/$orderId'
    | '/system/workshops'
    | '/vehiculos/$vehicleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/equipo'
    | '/login'
    | '/ordenes'
    | '/reportes'
    | '/repuestos'
    | '/vehiculos'
    | '/clientes/$customerId'
    | '/ordenes/$orderId'
    | '/system/workshops'
    | '/vehiculos/$vehicleId'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/equipo'
    | '/login'
    | '/ordenes'
    | '/reportes'
    | '/repuestos'
    | '/vehiculos'
    | '/clientes_/$customerId'
    | '/ordenes_/$orderId'
    | '/system/workshops'
    | '/vehiculos_/$vehicleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  EquipoRoute: typeof EquipoRoute
  LoginRoute: typeof LoginRoute
  OrdenesRoute: typeof OrdenesRoute
  ReportesRoute: typeof ReportesRoute
  RepuestosRoute: typeof RepuestosRoute
  VehiculosRoute: typeof VehiculosRoute
  ClientesCustomerIdRoute: typeof ClientesCustomerIdRoute
  OrdenesOrderIdRoute: typeof OrdenesOrderIdRoute
  SystemWorkshopsRoute: typeof SystemWorkshopsRoute
  VehiculosVehicleIdRoute: typeof VehiculosVehicleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordenes': {
      id: '/ordenes'
      path: '/ordenes'
      fullPath: '/ordenes'
      preLoaderRoute: typeof OrdenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repuestos': {
      id: '/repuestos'
      path: '/repuestos'
      fullPath: '/repuestos'
      preLoaderRoute: typeof RepuestosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehiculos': {
      id: '/vehiculos'
      path: '/vehiculos'
      fullPath: '/vehiculos'
      preLoaderRoute: typeof VehiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes_/$customerId': {
      id: '/clientes_/$customerId'
      path: '/clientes/$customerId'
      fullPath: '/clientes/$customerId'
      preLoaderRoute: typeof ClientesCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordenes_/$orderId': {
      id: '/ordenes_/$orderId'
      path: '/ordenes/$orderId'
      fullPath: '/ordenes/$orderId'
      preLoaderRoute: typeof OrdenesOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/workshops': {
      id: '/system/workshops'
      path: '/system/workshops'
      fullPath: '/system/workshops'
      preLoaderRoute: typeof SystemWorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehiculos_/$vehicleId': {
      id: '/vehiculos_/$vehicleId'
      path: '/vehiculos/$vehicleId'
      fullPath: '/vehiculos/$vehicleId'
      preLoaderRoute: typeof VehiculosVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  EquipoRoute: EquipoRoute,
  LoginRoute: LoginRoute,
  OrdenesRoute: OrdenesRoute,
  ReportesRoute: ReportesRoute,
  RepuestosRoute: RepuestosRoute,
  VehiculosRoute: VehiculosRoute,
  ClientesCustomerIdRoute: ClientesCustomerIdRoute,
  OrdenesOrderIdRoute: OrdenesOrderIdRoute,
  SystemWorkshopsRoute: SystemWorkshopsRoute,
  VehiculosVehicleIdRoute: VehiculosVehicleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
